# Generated by Django 2.2.16 on 2023-01-30 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20230129_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Напишите текст', verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Выберите дату публикации', verbose_name='Publication date')),
                ('author', models.ForeignKey(help_text='Укажите автора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('post', models.ForeignKey(blank=True, help_text='Укажите пост, к которой будет принадлежать', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post', verbose_name='Post')),
            ],
        ),
    ]
