# Generated by Django 2.2.16 on 2023-02-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230206_0958'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique follower',
        ),
    ]
